apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
   - ReadWriteOnce:
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo

---
apiVersion: app/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template: 
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: elderyde/projeto-database:1.0
        args:
        - "--ignore-db-dir=lost+found" 
        imagemPullPolicy: Alway
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql

          volumeMounys: 
          - name: mysql-dados
            mountParth: /var/lib/mysql
        volumes:
        - name: mysql-dados
          persistentVolumeClaim:
            claimName: mysql-dados 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app:php
spec:
  replicas: 6            
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:     
      containers:
      - name: php
        image: elderyde/projeto-backend:1.0
        imagePullPolicy: Alway
        ports: 
        - containerPort: 80
        
